# Generated by Django 5.2.3 on 2025-09-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_workerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='worker_profiles/'),
        ),
    ]
