# Generated by Django 6.0.2 on 2026-02-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_repair_otp_legacy_code_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='available_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='criminal_record_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='domestic_worker_visa_issued_by',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='educational_qualification',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='expected_benefits',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='expected_salary_full_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='expected_salary_part_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='has_criminal_record',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='health_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=10),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='nationality',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='passport_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='passport_number',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='police_clearance_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='preferred_work_locations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='visa_type',
            field=models.CharField(blank=True, choices=[('employment', 'Employment Visa'), ('visit', 'Visit Visa'), ('none', 'No Visa')], max_length=20),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='willing_to_relocate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='work_permit_status',
            field=models.CharField(blank=True, choices=[('not_applied', 'Not Applied'), ('applied', 'Applied'), ('approved', 'Approved')], max_length=20),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='work_preference',
            field=models.CharField(blank=True, choices=[('full_time', 'Full-Time'), ('part_time', 'Part-Time'), ('hourly', 'Hourly Basis'), ('live_in', 'Live-In'), ('live_out', 'Live-Out')], max_length=20),
        ),
    ]
