# Generated by Django 6.0.2 on 2026-02-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_workerprofile_alternate_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='employer_type',
            field=models.CharField(blank=True, choices=[('individual', 'Individual'), ('business', 'Business'), ('company', 'Company')], max_length=20),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='job_location',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='preferred_language',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
