# Generated by Django 6.0.2 on 2026-02-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_employerprofile_employer_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='id_proof_document',
            field=models.FileField(blank=True, null=True, upload_to='employer_documents/'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='emirates_id_document',
            field=models.FileField(blank=True, null=True, upload_to='worker_documents/'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='medical_fitness_certificate',
            field=models.FileField(blank=True, null=True, upload_to='worker_documents/'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='police_verification_certificate',
            field=models.FileField(blank=True, null=True, upload_to='worker_documents/'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='residency_visa_document',
            field=models.FileField(blank=True, null=True, upload_to='worker_documents/'),
        ),
    ]
