# Generated by Django 6.0.2 on 2026-02-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_customuser_role_compliancereport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentagencyprofile',
            name='verification_document',
            field=models.FileField(blank=True, null=True, upload_to='agency_documents/'),
        ),
    ]
