# Generated by Django 6.0.2 on 2026-02-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_supportservicemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyworkersubmission',
            name='experience_summary',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='agencyworkersubmission',
            name='job_role',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='agencyworkersubmission',
            name='verification_document',
            field=models.FileField(blank=True, null=True, upload_to='agency_worker_submissions/'),
        ),
    ]
