# Generated by Django 6.0.2 on 2026-02-28 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_agencyworkersubmission_experience_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='governmentprofile',
            name='verification_document',
            field=models.FileField(blank=True, null=True, upload_to='government_documents/'),
        ),
    ]
