# Generated by Django 6.0.2 on 2026-02-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_shortlistedworker'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='accommodation_provided',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='job',
            name='additional_benefits',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='job',
            name='background_verification_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='contract_type',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='job',
            name='emergency_contact_name_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_required',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='food_provided',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='job',
            name='full_time_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='hourly_wage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='language_requirements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='job',
            name='part_time_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='police_clearance_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='preferred_age_range',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='preferred_gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='preferred_nationality',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='job',
            name='recruitment_method',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='job',
            name='skills_required',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='job',
            name='specific_expectations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='work_environment_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='work_permit_sponsorship',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='job',
            name='work_schedule',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='workplace_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
