# Generated by Django 6.0.2 on 2026-02-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_accommodation_provided_job_additional_benefits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='application_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='job',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='job',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
