# Generated by Django 6.0.2 on 2026-02-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_savedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cover_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='supporting_document',
            field=models.FileField(blank=True, null=True, upload_to='application_documents/'),
        ),
    ]
