# Generated by Django 6.0.2 on 2026-02-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_job_review_notes_job_review_status_job_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='employer_signature_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='employer_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='worker_signature_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='worker_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
